### ISSUE TITLE
remove exposure value from aalcalc output

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#101]
this is not a useful measure of exposure value.

**Comment by johcarter** [comment]
removed from documentation

**Comment by benhayes21** [comment]
@hchagani-oasislmf - can you take a look at the overhead for this. 

The field is not there in the ORD output, so may just get removed through legacy

**Comment by hchagani-oasislmf** [comment]
@benhayes21 - using the PiWind model, I've found the following mean times for 1447 events each of 1000 samples with a maximum summary ID of 12598, determined over 24 trials:

Current implementation of `aalcalc`: 86.3 &pm; 1.5 s.
After removal of exposure value calculation: 83.5 &pm; 0.8 s.

The times lie within 2&sigma; of each other so I'm not confident there is much of a difference. However, perhaps for simplification and readability purposes, we should remove exposure value anyway. Especially if it is not useful, and isn't even in the ORD output.
