### ISSUE TITLE
new gulcalc allocrule for total peril loss using the multiplicative method

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#118]
Add support for combination of (sub-)peril losses in gulcalc using the following function

Total Loss = TIV * (1- (1-A)(1-B)(1-C) ..) where A, B and C are the damage ratios relating to the (sub-)perils of the same coverage.

Questions: 
1) How should the total loss be allocated back to the contributing sub-perils such that A Loss + B Loss + C Loss = Total Loss?
2) Are the full independent sub-peril losses required in a single run? If so, why?

Background: ktools has moved towards a single ground up loss stream (loss stream id 2) where losses come out at item (sub-peril-coverage) level. Total loss is then computed by a simple sum of the sub-peril losses from gulcalc in two places:

1)  In the Financial Module, in order to apply coverage level deductibles and limits, and
2)  summarycalc for ground up loss reports at coverage and higher levels of aggregation

This requires that the individual subperil losses from gulcalc sum to the correct combined total when using the loss stream.

ktools currently also supports the legacy gulcalc item (stream id 1/1) and gulcalc coverage (stream id 1/2) streams  in the same run, which do not require the items losses to sum to the combined coverage loss. FM uses the unadjusted item losses, and gul summarycalc uses the combined total loss from the coverages stream. However this functionality is planned to be deprecated.

**Comment by spasternakcorerlogiccom** [comment]
1 . To answer Q1: to my understanding sub-peril ground-up losses generally should be allocated back in the same way they are combined (order matter):

assuming:
A = min(1,A); B = min(1, max(0,1-A)); C = min(1,max(0,1-A-B));

A Loss = TIV * A;
B Loss = (TIV - A Loss) * B;
C Loss = (TIV - A Loss - B Loss) *C;
etc
Then A Loss + B Loss + C Loss + ...= Total Loss

**Comment by benhayes21** [comment]
@johcarter - can we pick this up as a part of the work on gulcalc in 2022H1

**Comment by johcarter** [comment]
we're now working on this functionality. @spasternak-clgx sorry for not responding, issue was on the backlog a long time.  The original back-allocation approach was agreed in a working group and we have recently reviewed your suggestion.  Any approach where order matters involves sorting the losses in stream which we think will have a detrimental effect on performance and we don't feel its worth the performance hit. So for this readon we are proposing to stick with the in-proportion back-allocation which is agnostic to order. FYI @mtazzari

**Comment by mtazzari** [comment]
This feature is now implemented in `gulpy` after merging PR https://github.com/OasisLMF/OasisLMF/pull/1098
