### ISSUE TITLE
Occurrence file format

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/ktools#12]
The occurrence_date_id calculated by `occurrencetobin` for event dates doesn't match the example given in ktools.pdf or the value as calculated by other software. Example for 1978-05-16.
 - ktools.pdf: 28626 or 28616
 - Excel: 28625
 - Python: 28624
 - [Timeanddate.com](https://www.timeanddate.com/date/durationresult.html?d1=01&m1=01&y1=1900&d2=16&m2=5&y2=1978): 28624
 - occurrencetobin: 28565

ktools.pdf says:

> “For example, 28626 days relative to a base date of 0/1/1900 is 16/5/1978.”

and

> “Using a base date of 1/1/1900 the integer 28616 is interpreted as 16/5/1978.”

Ignoring the fact that there may be typos, the output of occurrencetobin doesn't come close to those values.

Create test file occurrence.csv.
```
event_id,period_no,occ_year,occ_month,occ_day
0,0,78,5,16
0,0,1978,5,16
```
Convert to binary.
```
occurrencetobin -P 100 < occurrence.csv  > occurrence.bin
hexdump occurrence.bin
```
Output.
```
0000000 0001 0000 0064 0000 0000 0000 0000 0000
0000010 6f95 0000 0000 0000 0000 0000 065d 000b
0000020
```

0x6f95 is 28565 and 0x65d000b is 106758155. Neither of them match the values in the docs.

Excel says that between 1900-01-01 and 1978-05-16 there are 28625 days.
Python says that it’s 28624.

So as far as I can tell, the base date in `occurrencetobin` isn't 01/01/1900, it's 01/01/0000, but even then the calculated id is still a long way from its definition. Could the docs be amended to be consistent with the implementation, or vice-versa?

Where does the occ_date_id get used? I know that period_id is used for PLT or LEC calcs but I'm not sure whether occ_date_id really matters.

**Comment by benhayes21** [comment]
closing - stale issue
