### ISSUE TITLE
Investigate high memory use in leccalc

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#130]

**Comment by benhayes21** [comment]
I'll set up an example in PiWind to demonstrate

**Comment by benhayes21** [comment]
if you run the following oasislmf command for PiWind

`oasislmf model run -a analysis_settings_lec_test.json -d model_data/PiWind/ -x tests/inputs/SourceLocOEDPiWind.csv --ktools-alloc-rule-gul 0`

with this analysis settings file `

{
    "analysis_tag": "lec_test",
    "source_tag": "MDK",
    "model_version_id": "PiWind",
    "module_supplier_id": "OasisLMF",
    "number_of_samples": 100,
    "gul_threshold": 0,
    "gul_output": true,
    "il_output": false,
    "ri_output": false,
    "model_settings": {
        "event_set": "p",
        "event_occurrence_id": "lt"
    },
    "gul_summaries": [
        {
            "id": 1,
	    "oed_fields": ["PortNumber","AccNumber","LocNumber"],
            "lec_output": true,
            "leccalc": {
                "full_uncertainty_aep": true,
                "full_uncertainty_oep": true,
                "return_period_file": true
            }
        }
    ]
}

`

you will see a very high memory usage in leccalc. This occurs when granular lec outputs are requested (in this case location) with higher numbers of samples (100 here)

**Comment by hchagani-oasislmf** [comment]
Thanks @benhayes21, that has shown the issue well. The problem occurs in `leccalc.cpp`, where `map<outkey2, OASIS_FLOAT> agg_out_loss` and `map<outkey2, OASIS_FLOAT> max_out_loss` are filled. Every `summary_id` creates a new `outkey2`, so requesting higher granularity causes memory use to blow up.

Summary IDs could be out of order from `summarycalc` so it is not possible to process data as IDs are encountered. No solution yet. Intend to come back to this after dealing with other `ktools` issues.

**Comment by hchagani-oasislmf** [comment]
Summary of discussions with @sstruzik:

1. Combine `map<outkey2, OASIS_FLOAT> agg_out_loss` and `map<outkey2, OASIS_FLOAT> max_out_loss` into a single `map<outkey2, pair<OASIS_FLOAT, OASIS_FLOAT>>` object. This should reduce memory use by a factor of around 2 and is relatively straight forward to implement.
2. Investigate whether creating `map<int, lossvec> items`, for example, is required when performing numerical calculations. There may be a more efficient way of filling the aforementioned `agg_out_loss` and `max_out_loss` maps.
3. Write `summarycalc` output in chunks demarcated by a range of summary IDs. This would create files for each range that could then be processed separately by `aalcalc`, `leccalc`, `pltcalc` and `eltcalc`. The implementation of this should solve this issue, although it is quite extensive as it requires changes to five binaries.

**Comment by hchagani-oasislmf** [comment]
With reference to PR https://github.com/OasisLMF/ktools/pull/195, `map<outkey2, OASIS_FLOAT> agg_out_loss` and `map<outkey2, OASIS_FLOAT> max_out_loss` have been combined into a single `std::vector<std::map<outkey2, OutLosses>> out_loss` object. The new `OutLosses` struct has been defined as follows (`leccalc.h` L47-62):

```
struct OutLosses {
        OutLosses() {
                agg_out_loss = 0;
                max_out_loss = 0;
        }
        OASIS_FLOAT agg_out_loss;
        OASIS_FLOAT max_out_loss;

        OASIS_FLOAT GetAggOutLoss() {
                return agg_out_loss;
        }

        OASIS_FLOAT GetMaxOutLoss() {
                return max_out_loss;
        }
};
```

The member functions `GetAggOutLoss()` and `GetMaxOutLoss()` can be called to return the aggregate and maximum losses respectively. The two-element vector around this map are for `sidx = -1` and `sidx > 0`. The separation of these two groups of sample IDs should help with optimisation as there is no need to do it separately within different methods of the aggreports class.

**Comment by hchagani-oasislmf** [comment]
Rather than writing the output from `summarycalc` in chunks, it was decided that creating a summary index file would have less impact on downstream executables.
