### ISSUE TITLE
Handle Invalid Id lookups in getmodel

### ISSUE THREAD

**Issue by sambles** [OasisLMF/ktools#133]
If there is a mismatch between the **model_data** and ids in the generated oasis files then getmodel will fail with a segmentation Fault. 

* Add a check to getmodel or catch and report a more helpful error message.

### Recent Example: 
The model data vulnerability_id's are suffixed with `000`  so **11102000**, but the lookup python class is returning the id's without these and look like **11102**
```
vulnerability_id,intensity_bin_id,damage_bin_id,probability                                                                                                    
11101000, 1, 1, 1.0000000000e+00
11101000, 2, 1, 8.0000001192e-01
11101000, 2, 2, 5.9265694581e-03
   ...
11102000, 1, 1, 1.0000000000e+00                                                                                                                               
11102000, 2, 1, 8.0000001192e-01
11102000, 2, 2, 5.9780720621e-03
11102000, 2, 3, 5.9780720621e-03
11102000, 2, 4, 5.9780720621e-03
```

**Comment by hchagani-oasislmf** [comment]
Error message is now less vague than segmentation fault, and highlights possible differences between vulnerability IDs in items and vulnerability files.
