### ISSUE TITLE
Remove or replace analytical mean EP in wheatsheaf EP output

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/ktools#14]
The wheatsheaf AEP/OEP output currently starts with a block of data corresponding to the analytical mean EP curve with `sid = -1`.  This is misleading because one would expect to find the wheatsheaf mean, i.e. the mean of the values contained further down in the file, not the results of a completely different method. In some cases it may be barely noticeable but for some data the wheatsheaf mean and analytical mean EP curves are completely different as shown in the plot below.

![image](https://user-images.githubusercontent.com/15981535/35685353-63047d00-0761-11e8-88ae-3d22bdc3a5cd.png)

I understand there is a preference for the full uncertainty EP curve, however, the other methods are useful when trying to understand differences between platforms and we would like them to remain available if possible.

**Comment by carlfischerjba** [comment]
Our view is that it would be useful to include the wheatsheaf mean in the wheatsheaf output, but if that isn't possible then removing the analytical mean from the wheatsheaf output would avoid confusion.

**Comment by carlfischerjba** [comment]
Ben had concerns about repurposing the special sid -1 because it is used to refer to the analytical mean elsewhere. Another special value would be perfectly acceptable, although I would argue that if -1 corresponds to mean and -2 to standard deviation then using them to refer to the mean and standard deviation of the wheatsheaf in the context of the wheatsheaf output should be pretty clear.

**Comment by benhayes21** [comment]
closing...sidx -1 removed
