### ISSUE TITLE
sidx -3 values in loss stream

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#157]
The TIV value, represented by the sidx -3 value in the loss stream, are being double counted where we have multi peril models. Historically this was accounted for by the coverage stream but since mving to the loss stream, TIVs will be double counted for multi peril models as the sidx is at item level.

**Comment by johcarter** [comment]
Its necessary to use an allocation rule different from 0 for multi-peril models. 1 will cap the sum of loss to the TIV, 2 will take the maximum (equal to the TIV).   Can you explain where the problem is arising?

**Comment by benhayes21** [comment]
Not applicable
