### ISSUE TITLE
Include variation between samples in the AAL standard deviation

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/ktools#18]
Related to #16 as discussed with @benhayes21 and @mpinkerton-oasis.

There are two types of uncertainty in the AAL: between samples and between years. The standard deviation of mean losses from the YLT reflects the variation between years while the standard deviations reported in the YLT reflect the variation between samples for a given year.

The current implementation of `aalcalc`/`aalsummary` seems to only report the variation between years, i.e. the standard deviation of mean losses from the YLT. In our own software we report three standard deviations: between year, between samples, and total, to avoid ambiguity, but I can't comment on whether or how they are used in practice so please take this as a suggestion or low-priority feature request.

One way to get the total uncertainty is to take the standard deviation across all years and samples. This isn't ideal as it requires storing sampled losses for every year at the given aggregation level (portfolio, policy, location...). A lighter-weight alternative is to do `total_variance = mean(year_variances) + variance(year_means)` (square root if you want the standard deviation). This can be calculated with the means and standard deviations already available in the YLT.

The total variance formula only works for population variances, not for sample variances, so there are some corrective factors to apply based on number of samples and number of years when using sample variances, but this is negligible for if the number of samples and years is high.

```c#
// We work with sample variances (dividing by n-1) instead of population variances (dividing by n).
// The formula total variance = withinYearVariance + betweenYearVariance is only valid for population variances.
// The corrective factors below account for this.
withinYearVariance = mean(annualLossVariances);
betweenYearVariance = variance(annualMeanLosses);
numYearsCorrection = (numberOfYears - 1) / numberOfYears;
numSamplesCorrection = (numberOfSamples - 1) / numberOfSamples;
totalCorrection = (numberOfSamples * numberOfYears - 1) / (numberOfSamples * numberOfYears);

totalVariance = (withinYearVariance * numSamplesCorrection + betweenYearVariance * numYearsCorrection) / totalCorrection;
```

**Comment by johcarter** [comment]
We now calculate the total variation (3.0.0) and this is what you get in aalcalc type 2 standard deviation

**Comment by carlfischerjba** [comment]
Thanks, @johcarter. Will report back when we've been able to test.

**Comment by mpinkerton-oasis** [comment]
Closed as per Joh's comment
