### ISSUE TITLE
Some failures lead to missing events

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/ktools#19]
If a model run causes a component to fail, likely due to out if memory exceptions, then the ktools components exit without emitting an error.

**Comment by mpinkerton-oasis** [comment]
After discussion with Ben M, possible approaches are:
- Add more exception handling to the ktools components to trap and log failures.
- Add explicit logging that will record the successful completion of each step for each event. This can then be reconciled at the end of the analysis with the events list to guarantee that all events were processed.

Further investigation of these approaches is the next step.

**Comment by bmatharu** [comment]
Added a new module ktgetmem which does the following:

**Comment by bmatharu** [comment]
It first checks to see if we are running in docker and memory limit has been set - if so it a per process limit which is just less than the memory limit divided by the number of cores supplied as a parameter. If this exceeded a bad_alloc exception occurs.

Also added an exception handler to trap segmentation faults

**Comment by bmatharu** [comment]
If no memory limit is set then it gets the amount of free memory and splits that as a limit per core

**Comment by sambles** [comment]
To enable this feature in worker images `0.396.0` add the following environment variable when running the docker container.

`OASIS_API_KTOOLS_MEMORY_LIMIT=True`

If not set it will default to False

**Comment by mpinkerton-oasis** [comment]
@bmatharu is this complete now? If so, can you close.
