### ISSUE TITLE
getmodel in disaggregation mode - inconsistent generation of input files

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#20]
In disaggregation_test branch;
getmodel -d is reading in the aggregate items file and generating the standard ktools items file with disaggregated items on the fly, and writing it to the input folder. The problem is that it is using hidden rules to proportion out the tiv from the coverage file, and assign a coverage id from the pre-generated coverage file.

So you have a coverage and aggregate item file generated outside ktools, and the items file generated in ktools at model execution.  This disconnect in how the item file is generated will likely cause consistency problems with the other input files.

It would be better to strip the item file generation out of getmodel -d, and put it in a separate 'to bin' component that the front end system uses along with all the other input files.

**Comment by johcarter** [comment]
The assignment of coverage id in the generation of the items file appears to be wrong, in that it will assign the same coverage id to multiple disaggregated items when num items > 1, rather than distinct coverage ids. although the tiv is the same for each, this will cause capping of loss in gulcalc for the sum of the items to tiv/numitems which will be incorrect.

**Comment by sr-murthy** [comment]
I assume you are referring to the items CSV. The MDK sets coverage ID for an item as its (location ID, coverage type ID) in the sequence of all items. So for the FM7 test case we have
```
item_id,coverage_id,areaperil_id,vulnerability_id,group_id
1,1,1,1,1
2,2,1,2,1
3,3,1,3,1
4,4,1,4,1
5,5,2,1,2
6,6,2,2,2
7,7,2,3,2
8,8,2,4,2
```
This seems correct to me - the exposure has four coverage types: buildings (1) , other structures (2), contents (3), time (4), and there are two groups of four rows here, the first group for loc. 1, the second for loc. 2. If I add the loc. ID and coverage type columns this file can be written as
```
loc_id,coverage_type_id,item_id,coverage_id,areaperil_id,vulnerability_id,group_id
1,1,1,1,1,1,1
1,2,2,2,1,2,1
1,3,3,3,1,3,1
1,4,4,4,1,4,1
2,1,5,5,2,1,2
2,2,6,6,2,2,2
2,3,7,7,2,3,2
2,4,8,8,2,4,2
```
Coverage ID is being correctly as the ID for unique (loc. ID, cov. type ID) combinations.

**Comment by benhayes21** [comment]
@johcarter - is this still relevant?

**Comment by johcarter** [comment]
@benhayes21 i think we should keep it on the backlog until we know if the work done on this disaggregation branch is going to be useful
