### ISSUE TITLE
Output ImpactedNumLocs field in Sample Event Loss Table

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#207]
Currently, the Sample Event Loss Table (SELT) is missing the `ImactedNumLocs` field. It is possible to reconstruct this field from `gul_summary_map.csv`. However, this file is not part of the ktools kernel yet.

**Comment by johcarter** [comment]
This is an optional field so we won't put it in Oasis output unless priority changes
