### ISSUE TITLE
CSV header rows with whitespace and quotation marks are incompatible with Pandas

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/ktools#22]
The various "...tocsv" tools generate CSV header rows with quotation marks around each column name, and whitespace between them. For example, `gulsummaryxreftocsv` generates:

```
"coverage_id", "summary_id", "summaryset_id"
1, 1, 1
2, 1, 1
...
```
Some CSV readers, notably the Python Pandas package, expect header rows to contain only the names and delimiting commas - no whitespace or quotation marks. Using the above example of gulsummaryxref with pandas, the second and third column names include both the quotation marks and leading whitespace:

```
>>> df = pd.read_csv("gulsummaryxref.csv")
>>> df.columns
Index([u'coverage_id', u' "summary_id"', u' "summaryset_id"'], dtype='object')
>>> df['summary_id']
Traceback (most recent call last):
...
KeyError: 'summary_id'
```

If the quotation marks are removed from the raw CSV, but not the whitespace, Pandas still stubbornly includes the whitespace around each name:

```
>>> df = pd.read_csv("gulsummaryxref2.csv")
>>> df.columns
Index([u'coverage_id', u' summary_id', u' summaryset_id'], dtype='object')
```

Changing the "...tocsv" format to the following, with no quotation marks or whitespace, should ensure compatibility:

`coverage_id,summary_id,summaryset_id`

On a similar note, the tools also include whitespace between each data field in the output CSV. This also confuses Pandas when parsing string data (though not numerical). Without checking, I'm not sure if any of the CSV files that ktools can generate currently include string data.

**Comment by mpinkerton-oasis** [comment]
@bmatharu this is really annoying and would be great to fix.

**Comment by bmatharu** [comment]
The naming convention for headers was choosen because the inital user base was primary Microsoft power users who like using MS Access and Excel. These products use field names in double quotes.
In python it should be trival to change the first line to conform to any format. It's not so easy for non programmers.

**Comment by mpinkerton-oasis** [comment]
The main issue is with the spaces as part of the delimiters - I don't think anything does this by default.

With regards the quoting, I think Excel only uses quotes if there are special characters in the field names or data. The latest version of Excel, at least, doesn't do it by default for simple data saved as CSV.

Bottom line is, I think a no quotes and no spaces would work everywhere.

**Comment by bmatharu** [comment]
All quoted headers removed.
