### ISSUE TITLE
Output SourceNumLocs and SourceExposure fields in Period Average Loss Table

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#221]
## Issue Description
Currently the Period Average Loss Table (PALT) is missing the `SourceNumLocs` field. It is possible to construct this field from `gul_summary_map.csv`. However, this file is not part of the ktools kernel yet.

## Version / Environment information
Follows from introduction of PALT (see PR https://github.com/OasisLMF/ktools/pull/218), which shall feature in ktools `v3.6.2`.

**Comment by hchagani-oasislmf** [comment]
The `SourceExposure` field has been removed (see PR https://github.com/OasisLMF/ktools/pull/248) as it was incorrectly calculated. This field should be the sum of the Total Insured Value (TIV) from input exposures. This value is given in the exposure summary report, but this report is currently not part of the ktools kernel.

**Comment by johcarter** [comment]
Optional ORD fields, we won't implement in Oasis unless priorities change
