### ISSUE TITLE
Missing fields in Moment Event Loss Table (MELT)

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#232]
## Issue Description
The following fields are currently missing and should be added to the Moment Event Loss Table (MELT):

- [x] `ChanceOfLoss` - `ktools v3.7.3` see PR https://github.com/OasisLMF/ktools/pull/254
- [ ] `SDLossInd`
- [ ] `SDLossCor`
- [x] `MaxLoss` - `ktools v3.7.4` see PR https://github.com/OasisLMF/ktools/pull/262
- [ ] `FootprintNumLocs`
- [x] `MeanImpactedExposure` - `ktools v3.7.1` see PR https://github.com/OasisLMF/ktools/pull/245
- [ ] `MeanNumLocs`
- [x] `MaxImpactedExposure` - `ktools v3.7.1` see PR https://github.com/OasisLMF/ktools/pull/245
- [ ] `MaxNumLocs`

## Version / Environment information
From introduction of MELT (see PR https://github.com/OasisLMF/ktools/pull/229), ktools `v3.6.4`.

**Comment by johcarter** [comment]
Optional ORD outputs - will not implement in Oasis unless priorities change
