### ISSUE TITLE
Missing fields in Moment Period Loss Table (MPLT)

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#233]
## Issue Description
The following fields are currently missing and should be added to the Moment Period Loss Table (MPLT):

- [x] `Hour` - `ktools v3.7.0` see PR https://github.com/OasisLMF/ktools/pull/237
- [x] `Minute` - `ktools v3.7.0` see PR https://github.com/OasisLMF/ktools/pull/237
- [x] `ChanceOfLoss` - `ktools v3.7.3` see PR https://github.com/OasisLMF/ktools/pull/254
- [ ] `SDLossInd`
- [ ] `SDLossCor`
- [x] `MaxLoss` - `ktools v3.7.4` see PR https://github.com/OasisLMF/ktools/pull/262
- [ ] `FootprintNumLocs`
- [x] `MeanImpactedExposure` - `ktools v3.7.1` see PR https://github.com/OasisLMF/ktools/pull/245
- [ ] `MeanImpacedNumLocs`
- [x] `MaxImpactedExposure` - `ktools v3.7.1` see PR https://github.com/OasisLMF/ktools/pull/245
- [ ] `MaxImpactedNumLocs`

## Version / Environment information
From introduction of MPLT (see PR https://github.com/OasisLMF/ktools/pull/229), ktools `v3.6.4`.

**Comment by johcarter** [comment]
Optional ORD outputs - will not implement in Oasis unless priorities change
