### ISSUE TITLE
Missing fields in Sample Period Loss Table (SPLT)

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#234]
## Issue Description
The following fields are currently missing and should be added to the Sample Period Loss Table (SPLT):

- [x] `Hour` - `ktools v3.7.0` see PR https://github.com/OasisLMF/ktools/pull/237
- [x] `Minute` - `ktools v3.7.0` see PR https://github.com/OasisLMF/ktools/pull/237
- [ ] `ImpactedNumLocs`

## Version / Environment information
From introduction of SPLT (see PR https://github.com/OasisLMF/ktools/pull/229), ktools `v3.6.4`.

**Comment by hchagani-oasislmf** [comment]
While it is possible to construct the `ImpactedNumLocs` field from `gul_summary_map.csv`, it is not currently part of the ktools kernel. Moving issue to backlog.

**Comment by johcarter** [comment]
Optional ORD outputs - will not implement in Oasis unless priorities change
