### ISSUE TITLE
AAL Calc producing incorrect results

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#25]
When running aalcalc against a given summarycalc output, the results do not look correct. I'd expect to join the summarycalc output with the occurrence file, sum the losses and divide by the total number of periods to get the AAL but this is not the case.

Som other reports of GR losses > GU Losses for AAL from some users as well - to be investigated but might be related.

**Comment by johcarter** [comment]
This has been fixed to produce the correct results for  event_ids which occur multiple times across the periods in the occurrence file.
