### ISSUE TITLE
Zero loss EP curves should output records for required return periods

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#252]
## Issue Description

When the underlying losses are zero (e.g. no ground up losses attach to a policy layer) leccalc outputs an empty record set, whereas it would be better if the records were output with zero loss when a return period file is provided.  This is so the user knows that nothing has gone wrong in the model run and the risk is actually zero.

Even though there are no loss samples to generate the curve, the return period records are conceptually different to the samples that are used to generate the curve.

Zero loss records can only be output if a return period file is used. A record should be output for every required return period, whether it is zero or not, for both ordleccalc and leccalc please

## Steps to Reproduce (Bugs only)

To follow

**Comment by benhayes21** [comment]
it has also been noticed that when there are no type 1 losses, the header record in the leccalc output is missing.

I have created a dummy model with inputs that force all of the type 1 losses to be zero once passed through the fm, and this is the result:

```
ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ leccalc -K gulsummary -f gul_lec.csv 
ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ more gul_lec.csv 
summary_id,type,return_period,loss
1,1,10.000000,417475.281250
1,2,100.000000,632737.937500
1,2,50.000000,632737.937500
1,2,33.333332,632737.937500
1,2,25.000000,632737.937500
1,2,20.000000,632737.937500
1,2,16.666666,632737.937500
1,2,14.285714,632737.937500
1,2,12.500000,632737.937500
ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ leccalc -K ilsummary -f il_lec.csv 
ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ more il_lec.csv 
1,2,100.000000,39821.382812
1,2,50.000000,39821.382812
1,2,33.333332,39821.382812
1,2,25.000000,39821.382812
1,2,20.000000,39821.382812
1,2,16.666666,39821.382812
1,2,14.285714,39821.382812
1,2,12.500000,39821.382812
```

**Comment by benhayes21** [comment]
[test.tar.gz](https://github.com/OasisLMF/ktools/files/7627582/test.tar.gz)

**Comment by benhayes21** [comment]
dummy model attached above @hchagani-oasislmf

**Comment by hchagani-oasislmf** [comment]
> it has also been noticed that when there are no type 1 losses, the header record in the leccalc output is missing.
> 
> I have created a dummy model with inputs that force all of the type 1 losses to be zero once passed through the fm, and this is the result:
> 
> ```
> ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ leccalc -K gulsummary -f gul_lec.csv 
> ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ more gul_lec.csv 
> summary_id,type,return_period,loss
> 1,1,10.000000,417475.281250
> 1,2,100.000000,632737.937500
> 1,2,50.000000,632737.937500
> 1,2,33.333332,632737.937500
> 1,2,25.000000,632737.937500
> 1,2,20.000000,632737.937500
> 1,2,16.666666,632737.937500
> 1,2,14.285714,632737.937500
> 1,2,12.500000,632737.937500
> ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ leccalc -K ilsummary -f il_lec.csv 
> ben@ben:~/oasis/sandbox/cl_zero_lec/runs/test-files-20211130165156$ more il_lec.csv 
> 1,2,100.000000,39821.382812
> 1,2,50.000000,39821.382812
> 1,2,33.333332,39821.382812
> 1,2,25.000000,39821.382812
> 1,2,20.000000,39821.382812
> 1,2,16.666666,39821.382812
> 1,2,14.285714,39821.382812
> 1,2,12.500000,39821.382812
> ```

Created new issue https://github.com/OasisLMF/ktools/issues/259 for this.
