### ISSUE TITLE
Propagate ChanceOfLoss and MaxLoss fields through fmcalc

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/ktools#255]
## Issue Description
The [ORD](https://github.com/OasisLMF/OpenDataStandards) fields `ChanceOfLoss` and `MaxLoss` are calculated in `gulcalc` and propagated to the downstream components. These values are currently ignored by `fmcalc`, and are therefore not propagated for insurance and reinsurance losses when using `fmcalc`. However, they are available when using `fmpy`.

As `fmcalc` is legacy code, it is undetermined whether it is worth investing time in fixing this.

## Version / Environment information
ktools `v3.7.3`

**Comment by hchagani-oasislmf** [comment]
`fmcalc` is still used for comparison purposes, so it is worth spending the time to resolve this issue.

**Comment by benhayes21** [comment]
fmcalc can ignore but fmpy should pass through @sstruzik

**Comment by johcarter** [comment]
works in fmpy
