### ISSUE TITLE
Questions about sample index in leccalc

### ISSUE THREAD

**Issue by cdlhub** [OasisLMF/ktools#28]
- Based on `src/leccalc/leccalc.cpp`:`void processinputfile(...)`, I guessed that sample loss records are sorted in decreasing index order in the input stream. Am I correct?
- In `processinputfile(...)` code, there is a condition `if (sr.sidx != -2)`. What is a sample with index `-2`?
- In `processinputfile(...)` code, if sample loss records are sorted in decreasing sample index order, then the condition `if (sr.sidx != -2)` is always true because index -2 is after index 0 and then it is never read. Am I missing something? If not, could it be a bug?

  ```sh
  while (i != 0) {
      sampleslevelRec sr;
      i = fread(&sr, sizeof(sr), 1, stdin);
      if (i == 0) break;
      if (sr.sidx == 0) break;
      //				dolecoutput1(sh.summary_id, sr.loss,iter->second);					
      if (sr.sidx != -2) {
          if (sr.loss > 0.0 && processEvent == true) dolecoutputaggsummary(sh.summary_id, sr.sidx, sr.loss, iter->second,agg_out_loss,max_out_loss);
      }
  }
  ```

**Comment by johcarter** [comment]
sample index -2 is the standard deviation of loss which used to be reported in outputs. however this was changed and it is now dropped from summarycalc onwards. this code may be part obsolete but we will take a look.

**Comment by bmatharu** [comment]
The test in the while loop is a not equal to 0 therefore an sidx of -2 would come into the loop(assuming it was in the input stream)
But the reality is that you are correct in the sense that the input stream now no longer has a -2 sidx - we removed it in the summarycalc step so yes the conditional check can now be removed. I will remove it to clean up the code for the next release. Thanks

**Comment by cdlhub** [comment]
Yes, you are right that the while loop test is `i != 0`, however, inside the loop the code `if (sr.sidx == 0) break;` comes before `if (sr.sidx != -2)`. Hence, if sample index are sorted, it cannot be true.
Anyhow, this is not important anymore after your comment. Thank you for the clarification.

**Comment by cdlhub** [comment]
Also, what about sample with index 0? It appears not to be used in the calculation because of:

```sh
if (sr.sidx == 0) break;
```
Is it on purpose?

**Comment by bmatharu** [comment]
Yes it is on purpose - the confusion is that in the old days the was sidx = 0 was the mean  this is before ktools day - this was changed to -1 and now sidx 0 is used as a terminating condition for the set of records coming thru hence the break.
