### ISSUE TITLE
Precision of 4 byte floats in outputs

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#3]
The precision effects of using 4 byte floats are more apparent in fm losses and summary statistics (mean, stdev and TIV) for large portfolios as the numbers are very large and the results are being rounded to 6 significant figures. Is this an issue? We can consider moving to double precision if so.

**Comment by bmatharu** [comment]
Moving to double precision is an option but the volume of data will grown considerably - this may also be an issue.

**Comment by cdlhub** [comment]
Could it be set with a command line option flag like `--dprec` (float by default and double if `--dprec` is set)? The user could then decide on the fly, make comparisons and check impacts on numbers.

The code could use template for implementation.

**Comment by bmatharu** [comment]
Agreed it could be done but its just not on the plan at the moment I think we're planning something simpler which is to have a compile time #define of OASIS_FLOAT which could be changed to type double  etc.
