### ISSUE TITLE
Problem with c++ compiler when installing ktools 3.0.3 in Windows 7 64-bit

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#31]
the mingw toolchain doesnt install correctly and the compiler is shown as not being present at the ./configure stage

**Comment by johcarter** [comment]
![msys2](https://user-images.githubusercontent.com/11421733/51383724-270c7580-1b12-11e9-811d-906a5c7883cb.png)

**Comment by johcarter** [comment]
I can't replicate this problem but I noticed a pitfall in the process which is that even though I installed the 64-bit version of msys2, I got more than one application installed.  When the installation completes and it prompts you to launch the terminal, the version that is launched may not be 64bit.   It shows “mingw” not “mingw64” at the command prompt.  When I closed the terminal and launched the 64 bit version from the start menu (there was more than 1 version to choose from) it showed “mingw64” at the command prompt which is the correct version to use.  I then performed the pacman updates and installed packages and ktools in this terminal.

**Comment by DanielFEvans** [comment]
We bumped into this some months back on Windows 10 systems (Windows 7 was fine). The suspicion we had was that our virus scanner or some other piece of security software was not getting on well with Cygwin - it's apparently well known for not getting on with a variety of other pieces of software, and there are plenty of similar results on Google for other pieces of software.

(I have a vague recollection that the situation was so bad that even trying to compile a simple "Hello world" would fail; the output file was either not created or instantly deleted)

**Comment by johcarter** [comment]
is this still an issue for you, @DanielFEvans or can I close it?

**Comment by DanielFEvans** [comment]
@johcarter - I've not compiled on Windows for a long time! I think Oasis later decided that Windows wasn't supported by OasisLMF, and we've also moved away from supporting it ourselves.

**Comment by DanielFEvans** [comment]
(Plus, re-reading my comments, it looks like I suspected it was unrelated to Oasis anyway, so not sure what you could do)

**Comment by johcarter** [comment]
Thanks @DanielFEvans I think i'll close this one, then.
