### ISSUE TITLE
Potential bug in AAL calculation with -c flag turned on

### ISSUE THREAD

**Issue by jchhabra1C** [OasisLMF/ktools#321]
As `sidx` gets greater than `samplesize_`, the inner loop will not break and erroneous values are read into `mean` variable resulting in incorrect calculation of AAL based on samples.

https://github.com/OasisLMF/ktools/blob/e77fc2dd436a7b49841c0506b26eb374a4ecd836/src/aalcalc/aalcalc.cpp#L362

**Comment by hchagani-oasislmf** [comment]
@jchhabra1C, would you agree with the above?

**Comment by jchhabra1C** [comment]
Thanks for getting back. I was having this issue because I pulled the code before June 28 and this update should fix it https://github.com/OasisLMF/ktools/commit/5893b68a96af2f180c9143d1c01e03091bdff211#diff-17f95ddca6bfad4d8dacc1cec2f838f2b51b24331897ad4c56b617d7975e1ff3L169.
