### ISSUE TITLE
crossvalidation tool requires damagebin to have (deprecated) interval_type column

### ISSUE THREAD

**Issue by pslh** [OasisLMF/ktools#325]
## Issue Description
The crossvalidation tool halts with the error "Invalid data in line 1" if the "interval_type" column is not present.  The interval_type column is deprecated, and the validatedamagebin tool signals it's presence with the warning "Deprecated format: interval_type column no longer required."

I am using OASIS LMF LTS v 1.23.12 with ktools version 3.8.0 on Linux but inspecting [crossvalidation.cpp](https://github.com/OasisLMF/ktools/blob/master/src/crossvalidation/crossvalidation.cpp) lines 46 - 52 it would appear that the current master version behaves in the same way.

## Steps to Reproduce (Bugs only)

1. Create a damage_bin_dict.csv file without the _interval_type_ column
2. Run crossvalidation -d damage_bin_dict.csv -f footprint.csv -s vulnerability.csv

## Version / Environment information

Linux (Debian 10 "Buster")

OASIS LMF 1.23.12 (and I suspect this is still present in master)

unknown

## Example data / logs
[db.csv](https://github.com/OasisLMF/ktools/files/9535792/db.csv)
[dbi.csv](https://github.com/OasisLMF/ktools/files/9535793/dbi.csv)

**Comment by hchagani-oasislmf** [comment]
Hi @pslh, thank you for flagging this issue. I have submitted a PR that will fix the problem. Unless you have any objections, this will be published in the next release.

**Comment by pslh** [comment]
No objections from my side, thanks.
