### ISSUE TITLE
Number of affected risks output

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#365]
## Issue Description
There is a requirement to create a measure of the number of affected risks in an analysis. 

Proposal, to be discussed, is that we create a new output report which counts the number of summary_ids with a sidx `-1`value > 0 at event_id level.

supported by new python module summurypy in:
https://github.com/OasisLMF/OasisLMF/pull/1482

**Comment by johcarter** [comment]
We already have some ORD fields to report this information, rather than create a new report 
![image](https://github.com/OasisLMF/ktools/assets/11421733/a46cf2b9-dae9-4cf7-a986-368099421c55)

**Comment by benhayes21** [comment]
To discuss whether we can link through to gul summary map to get number of locations

**Comment by benhayes21** [comment]
can we recycle `-4` sidx for number of locations?

**Comment by hchagani-oasislmf** [comment]
> can we recycle `-4` sidx for number of locations?

I don't see why not. The downstream components either carry this `sidx` forward or discard it. This behaviour can be changed.
