### ISSUE TITLE
Gross loss > ground up loss under allocrule 2 caused by max deductibles

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#51]
e.g. 10000 location deductible with a pol max ded of 500. using allocrule 2 the adjusted location gross loss can exceed the ground up.

| LOC      | GU          |  GR          | EFF_DED | POL_MAX_DED | ADJ GR     |
|:---------|-----------|-----------|-----------|------------------|------------:|
| 1           | 41593     |    31593  | 10000     |                           |   33017     |
| 2           | 1257       |    0          | 1257       |                           |   0             |
| 3           | 1257       |    0          | 1257       |                           |   0             |
| 4           | **467590**   |  457590  | 10000     |                           |   **478217**   |
| POL      | 511735   |    489184 | 22550     |         500            |   511235   |

**Comment by johcarter** [comment]
How should this be handled?

**Comment by benhayes21** [comment]
@hchagani-oasislmf - can you see if this is still an issue in fmpy?

**Comment by benhayes21** [comment]
[account.csv](https://github.com/OasisLMF/ktools/files/7744638/account.csv)
[location.csv](https://github.com/OasisLMF/ktools/files/7744640/location.csv)

**Comment by johcarter** [comment]
I'm pretty sure this is fixed in fmpy, and an outstanding issue in ktools https://github.com/OasisLMF/ktools/issues/235

Can be closed because its a duplicate @benhayes21

**Comment by johcarter** [comment]
fixed in fmpy
