### ISSUE TITLE
create calcrule with ded1, 2 and 3 as amounts

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#52]
% TIV deductibles must be converted to amounts to go into deductible 1 field so that the TIV definition is for the whole policy not the impacted locations. need a rule based on calcrule 21 logic but with ded1 as an amount.

**Comment by sr-murthy** [comment]
Implemented in this PR

https://github.com/OasisLMF/OasisLMF/pull/336

Just need tests to pass

**Comment by sr-murthy** [comment]
Closing, as all related tests (FM8-9, FM40-41) pass

**Comment by johcarter** [comment]
this is to do with creating a new calcrule in fmcalc
