### ISSUE TITLE
sidx -3 weird behaviour across layers

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/ktools#68]
more details to follow

**Comment by johcarter** [comment]
sidx -3 is coming out as zero for ri net losses for certain locations and events. it should be coming out as 80% of gross. 

It should be showing a 20% gross loss in layer 1 with layers 2-16 showing a zero loss because a zero limit is being applied.  what is happening is a non-zero gross loss for all layers is being generated at the backallocation stage and hence the sum of layer losses exceeds the input gross loss.

is layer_id being ignored in the back allocation stage for sidx -3? the other samples are correct.

**Comment by johcarter** [comment]
the knock on effect of this behaviour is that other samples (non-zero) are being filtered out of summarycalc output because sidx -3 is zero.

**Comment by johcarter** [comment]
This issue is caused by inappropriate use of layers and is not a ktools bug. In the example provided, there are 16 layers used at levels 1, 2 and 3 as follows;
* Level 1 Locations grouping. Location losses are filtered according to the scope of the reinsurance contact by passing through losses of locations in scope of the reins (deductible =0) and setting all other losses to zero (limit = 0). Each layer represents a different reins contract of risk level (blank).
* Level 2 Locations are aggregated all together into one group and the % ceded terms are applied by layer
* Level 3 The 16 layers are carried forward to apply treaty occurrence terms.

The reason it fails is that back-allocation uses a single set of proportions which is defined by the aggregation tree (fm_programme).  When different losses are set to zero in different layers and then carried forward, this creates the need for different trees of back-allocation proportions for each layer, which is not currently supported.

The correct way to represent this structure is to use the aggregation tree defined in programme to group together the losses under the scope of each treaty (which do not overlap in this case).  Layers should only be used to apply the treaty terms where there is a genuine need for layers because the reins scope of two or more treaties overlaps, and to apply the final occurrence terms.

oasislmf needs to generate the reinsurance files differently so that layers are not created  unnecessarily. See https://github.com/OasisLMF/OasisLMF/issues/382 fyi  @mpinkerton-oasis @sambles 

@johcarter need to investigate exactly why layers work over two levels and not three in this case such that validation checks can be made on fm_input files.

**Comment by mpinkerton-oasis** [comment]
@johcarter should we close this and create a more specific issue for the work @bmatharu is doing?

**Comment by johcarter** [comment]
opened https://github.com/OasisLMF/ktools/issues/80
