### ISSUE TITLE
Typo in documentation: Replace eventfootprint.bin by footprint.bin

### ISSUE THREAD

**Issue by cdlhub** [OasisLMF/ktools#7]
`getmodel` specifications (4.1 Core Components - getmodel and 4 Reference Model Overview - getmodel) refers to input file `eventfootprint.bin`, where in the code of `getmodel.cpp` it uses macro `FOOTPRINT_FILE`, which is set to `static/footprint.bin` in `include/oasis.h`.

**Comment by bmatharu** [comment]
Thank you for the feedpack the typos have now been fixed
