### ISSUE TITLE
Add logging for each component in ktools

### ISSUE THREAD

**Issue by ndaqjn** [OasisLMF/ktools#87]
Trying to do a root-cause analysis on a failure appearing in ktools is right now is very difficult, since any logging information is not propagated outside of the container.

All of the components in the chain needs to have a common log format and the log entries needs to clearly indicate which component is logging. This log information needs also to be propagated back to the platform so it can be retrieved after the run has failed.

**Comment by sambles** [comment]
Released in [v3.2.1](https://github.com/OasisLMF/ktools/tree/v3.2.1)
Each process logs start and end states under `<run_dir>/log/<bin>_<pid>.log`

```
$ tree log/
log/
├── eve_2560.log
├── eve_2565.log
├── eve_2568.log
├── eve_2581.log
├── fmcalc_2567.log
├── fmcalc_2573.log
├── fmcalc_2575.log
├── fmcalc_2578.log
├── fmcalc_2579.log
├── fmcalc_2583.log
├── fmcalc_2586.log
├── fmcalc_2588.log
├── getmodel_2561.log
├── getmodel_2566.log
├── getmodel_2571.log
├── getmodel_2582.log
├── gulcalc_2563.log
├── gulcalc_2569.log
├── gulcalc_2574.log
├── gulcalc_2584.log
├── stderror.err
├── summarycalc_2529.log
├── summarycalc_2530.log
├── summarycalc_2531.log
├── summarycalc_2532.log
├── summarycalc_2541.log
├── summarycalc_2542.log
├── summarycalc_2543.log
├── summarycalc_2544.log
├── summarycalc_2553.log
├── summarycalc_2554.log
├── summarycalc_2555.log
└── summarycalc_2556.log

0 directories, 33 files
```

```
 $ cat log/getmodel_2571.log
INFO:getmodel:2571:starting process..
INFO:getmodel:2571:finishing process..
```
