### ISSUE TITLE
leccalc gives nonsense numbers when year-sample combination is too high

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/ktools#98]
If the number of samples used multiplied by the number of years in the model (from the occurrence file header record) is greater than the upper limit of a 4 byte integer (i.e. 2.147 billion) then the losses generated in leccalc are nonsense.

In the example that we're running we see negative sidx values, for example.

The example in question had 50,000 years in the model and using sample numbers over 42,949 causes the nonsense losses.

These are understood to be very high sample numbers but leccalc should really produce nothing and flag the error if the numbers are too high, rather than producing incorrect losses.

**Comment by hchagani-oasislmf** [comment]
The culprit appears to be the following:

```
                if (samplesize_) t = (OASIS_FLOAT)(totalperiods_ * samplesize_);
```

The conversion to `OASIS_FLOAT` takes place after the expression `totalperiods_ * samplesize_` is resolved. Therefore, as `totalperiods_` and `samplesize_` are both ints, the integer overflow behaviour above is witnessed.
